### ISSUE TITLE
As a Teacher I want to learn hoe to create gitHub user Stories

### ISSUE THREAD

**Issue by MirkoPelgrom65** [MirkoPelgrom65/fep2-rxjs-subject-example#1]
# User Story

## DoR
- [ ] Create a gitHub Project
- [ ] Create test issues

## Description
Play around with issues in gitHub to get more familiar with them.

## Tasks
- [ ] #2
- [ ] Add label to Issue
- [ ] Create MilesStones
- [ ] Add Milestone to issue
- [ ] Create Sprints
- [ ] Add Sprint to issue

## DoD
- [x] I have completed creatting an issue 
- [ ] I have added the correct labels to the issue
- [ ] I have added the correct milestone to the issue
- [ ] I have added the correct Repository to the issue
- [ ] I have added the correct Sprint to the issue

**Comment by MirkoPelgrom65** [comment]
# DoR
- [ ] Create a gitHub Project
- [ ] Create test issues
